### ISSUE TITLE
Case insensitive match

### ISSUE THREAD

**Issue by wookayin** [omerdn1/alfred-kill-process#1]
Hi, thanks for the great workflow. One suggestion: I think this workflow should match candidates in a **case-insensitive manner** rather than case-sensitive manner (the current behavior). It would be more convenient to kill some macOS apps because most of the applications would start with a Capital letter (e.g., `/Application/Google Chrome.app`, should be matched by `chrome`)

**Comment by omerdn1** [comment]
Thank you for bringing this to my attention. I agree that this should have been the correct behaviour.
Fixed in 19fceb3ba462413af40eaa0cb18a83db381b054f
